import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Основы IT',
      collapsible: true,
      collapsed: false,
      items: [
        'basics/what-is-software',
        'basics/how-computer-works',
        'basics/what-is-network',
        {
          type: 'category',
          label: 'Что такое программирование',
          link: {type: 'doc', id: 'basics/what-is-programming'},
          collapsible: true,
          collapsed: true,
          items: [
            'basics/what-is-os',
            'basics/git-overview',
          ],
        },
        {
          type: 'category',
          label: 'Кто такой системный аналитик',
          link: {type: 'doc', id: 'basics/who-is-system-analyst'},
          collapsible: true,
          collapsed: true,
          items: [
            'basics/what-is-sdlc',
            'basics/what-is-testing',
            'basics/what-is-sa-documentation',
            'basics/it-roles',
            'basics/sa-day-in-life',
          ],
        },
        {
          type: 'category',
          label: 'Клиент-серверная архитектура',
          link: {type: 'doc', id: 'basics/client-server-basics'},
          collapsible: true,
          collapsed: true,
          items: [
            'basics/what-is-protocol',
            'basics/what-is-api',
            'basics/what-is-app-types',
          ],
        },
        {
          type: 'category',
          label: 'Что такое данные, информация, знания',
          link: {type: 'doc', id: 'basics/what-is-data'},
          collapsible: true,
          collapsed: true,
          items: [
            'basics/what-is-database-basics',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Работа с требованиями',
      collapsible: true,
      collapsed: false,
      items: [
        'requirements/what-is-requirement',
        'requirements/stakeholder-communication',
        'requirements/user-stories',
        'requirements/bdd-scenarios',
        'requirements/functional-requirements-detailed',
        'requirements/nfr',
        'requirements/prioritization',
        'requirements/use-cases-formal',
        'requirements/user-story-mapping-req',
        'requirements/acceptance-criteria-detailed',
        'requirements/requirements-validation',
        'requirements/change-management',
        'requirements/srs',
        'requirements/traceability',
        'requirements/decision-log',
      ],
    },
    {
      type: 'category',
      label: 'Моделирование',
      collapsible: true,
      collapsed: false,
      items: [
        'modeling/what-is-model',
        'modeling/use-case-diagram',
        'modeling/sequence-diagram',
        'modeling/bpmn',
        'modeling/er-diagrams',
        'modeling/state-diagram',
        'modeling/class-diagram',
        'modeling/bpmn-advanced',
        'modeling/c4-context',
        'modeling/c4-container',
        'modeling/user-story-mapping',
        'modeling/impact-mapping',
        'modeling/dfd',
        'modeling/component-diagram',
      ],
    },
    {
      type: 'category',
      label: 'Архитектура',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'architecture/what-is-architecture',
        'architecture/layered-architecture',
        'architecture/monolith-vs-microservices',
        'architecture/microservices-patterns',
        'architecture/cqrs',
        'architecture/eda-detailed',
        'architecture/solid',
        'architecture/adr',
        'architecture/ddd-intro',
        'architecture/hexagonal-architecture',
        'architecture/saga-pattern',
        'architecture/strangler-fig',
        'architecture/logging',
        'architecture/monitoring',
        'architecture/tracing',
        'architecture/authorization',
        'architecture/resilience-patterns',
        'architecture/caching',
      ],
    },
    {
      type: 'category',
      label: 'Процессы разработки',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'process/sdlc-models',
        'process/scrum-basics',
        'process/kanban-basics',
        'process/scrum-detailed',
        'process/estimation',
        'process/retrospectives',
        'process/agile-requirements',
        'process/babok-overview',
        'process/requirements-management',
        'process/stakeholder-analysis',
        'process/cost-benefit-analysis',
        'process/risk-management',
      ],
    },
    {
      type: 'category',
      label: 'Soft skills',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'soft/soft-skills',
        'soft/critical-thinking',
        'soft/business-writing',
        'soft/facilitation',
        'soft/business-writing-deep',
        'soft/workshop-techniques',
        'soft/negotiations',
        'soft/mentoring',
        'soft/coaching',
      ],
    },
    {
      type: 'category',
      label: 'Интеграция',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index', title: 'Интеграция'},
      items: [
        'integration/api-rest-basics',
        'integration/api-openapi',
        'integration/api-design-detailed',
        'integration/api-versioning',
        'integration/api-auth',
        'integration/api-soap-wsdl',
        'integration/async-message-queue',
        'integration/rabbitmq',
        'integration/kafka',
        'integration/event-driven-architecture',
        'integration/event-storming',
        'integration/enterprise-integration-patterns',
        'integration/api-gateway',
        'integration/event-storming-advanced',
      ],
    },
    {
      type: 'category',
      label: 'Данные и БД',
      collapsible: true,
      collapsed: false,
      items: [
        'data/what-is-database',
        'data/sql-basics',
        'data/json-xml',
        'data/normalization',
        'data/nosql',
        'data/data-modeling',
        'data/dwh-basics',
        'data/etl-basics',
        'data/data-migration',
        'data/api-first-design',
      ],
    },
    {
      type: 'category',
      label: 'Специализации',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'specialization/ba-vs-sa',
        'specialization/data-analyst-path',
        'specialization/solution-architect-path',
        'specialization/industry-analytics',
        'specialization/ai-analyst-intro',
        'specialization/ai-ml-basics',
        'specialization/ai-ml-eda',
        'specialization/ai-ml-requirements',
        'specialization/ai-ml-data',
        'specialization/ai-ml-metrics',
        'specialization/ai-llm-rag',
        'specialization/ai-ethics',
        'specialization/ai-ml-architecture',
        'specialization/ai-agents-intro',
        'specialization/ai-agents-multi',
        'specialization/ai-agents-mcp',
        'specialization/ai-agents-dev',
        'specialization/fintech-analyst-path',
        'specialization/fintech-payments',
        'specialization/fintech-regulation',
        'specialization/fintech-protocols',
        'specialization/fintech-ledger',
        'specialization/fintech-reconciliation',
        'specialization/fintech-open-banking',
        'specialization/fintech-fraud',
        'specialization/fintech-lending',
        'specialization/ecommerce-retail-path',
        'specialization/ecommerce-oms',
        'specialization/ecommerce-catalog',
        'specialization/ecommerce-pricing',
        'specialization/ecommerce-marketplace',
        'specialization/ecommerce-fulfillment',
        'specialization/ecommerce-loyalty',
        'specialization/ecommerce-analytics',
        'specialization/telecom-path',
        'specialization/telecom-bss-oss',
        'specialization/telecom-billing',
        'specialization/telecom-crm-order',
        'specialization/telecom-provisioning',
        'specialization/telecom-regulations',
        'specialization/telecom-mvno',
        'specialization/telecom-5g-iot',
        'specialization/govtech-path',
        'specialization/govtech-gis-architecture',
        'specialization/govtech-portal',
        'specialization/govtech-smev',
        'specialization/govtech-import-substitution',
        'specialization/govtech-security',
        'specialization/govtech-procurement',
        'specialization/govtech-edo',
        'specialization/medtech-path',
        'specialization/medtech-emk',
        'specialization/medtech-mis',
        'specialization/medtech-lis',
        'specialization/medtech-pharma',
        'specialization/medtech-telemedicine',
        'specialization/medtech-pacs',
        'specialization/medtech-regulations',
      ],
    },
  ],
};

export default sidebars;
