import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  techSidebar: [
    {
      type: 'category',
      label: 'Технологии',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'astra-linux',
        'cdn',
        'docker',
        'elasticsearch',
        'emias',
        'erp',
        'geodata',
        'grpc',
        'http',
        'llm',
        'postgresql',
        'prometheus',
        'recommendation',
        'redis',
        'smev',
        'tms',
        'vector-database',
        'wms',
      ],
    },
    {
      type: 'category',
      label: 'Инструменты',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        {
          type: 'category',
          label: 'Управление проектами',
          collapsible: true,
          collapsed: true,
          items: ['jira', 'confluence'],
        },
        {
          type: 'category',
          label: 'Моделирование и дизайн',
          collapsible: true,
          collapsed: true,
          items: ['drawio', 'figma', 'miro', 'plantuml'],
        },
        {
          type: 'category',
          label: 'API и интеграции',
          collapsible: true,
          collapsed: true,
          items: ['postman', 'curl', 'kafka', 'rabbitmq'],
        },
        {
          type: 'category',
          label: 'Контейнеризация и DevOps',
          collapsible: true,
          collapsed: true,
          items: ['docker', 'kubernetes', 'git'],
        },
        {
          type: 'category',
          label: 'ML/AI инструменты',
          collapsible: true,
          collapsed: true,
          items: ['huggingface', 'langchain', 'mlflow'],
        },
        {
          type: 'category',
          label: 'Базы данных',
          collapsible: true,
          collapsed: true,
          items: ['dbeaver'],
        },
        {
          type: 'category',
          label: 'Мобильные и игровые платформы',
          collapsible: true,
          collapsed: true,
          items: ['appsflyer', 'firebase', 'unity'],
        },
        {
          type: 'category',
          label: 'Инструменты разработчика',
          collapsible: true,
          collapsed: true,
          items: ['browser'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Стандарты и протоколы',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'crypto',
        'diameter',
        'dicom',
        'edi',
        'hl7',
        'iso20022',
        'mcp',
        'openapi',
        'pci-dss',
        'swift',
        'tmforum',
        'websocket',
      ],
    },
    {
      type: 'category',
      label: 'Методологии и фреймворки',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index'},
      items: [
        'scrum',
        'photon',
      ],
    },
  ],
};

export default sidebars;
