const LABELS: Record<string, string> = {
  'basics/what-is-software': 'Что такое программное обеспечение',
  'basics/how-computer-works': 'Как работает компьютер',
  'basics/what-is-programming': 'Что такое программирование',
  'basics/who-is-system-analyst': 'Кто такой системный аналитик',
  'basics/client-server': 'Клиент-серверная архитектура',
  'basics/client-server-basics': 'Клиент-серверная архитектура',
  'basics/what-is-api': 'Что такое API',
  'basics/what-is-protocol': 'Что такое протокол взаимодействия',
  'basics/it-roles': 'Какие есть роли в IT-команде',
  'basics/sa-day-in-life': 'Как выглядит рабочий день системного аналитика',
  'basics/what-is-data': 'Что такое данные, информация, знания',
  'basics/what-is-network': 'Что такое интернет и компьютерная сеть',
  'basics/what-is-os': 'Что такое операционная система',
  'basics/what-is-app-types': 'Какими бывают приложения: веб, мобайл, десктоп',
  'basics/what-is-sdlc': 'Как разрабатывают программное обеспечение (SDLC)',
  'basics/what-is-database-basics': 'Как устроены базы данных',
  'basics/what-is-testing': 'Как тестируют программное обеспечение',
  'basics/what-is-sa-documentation': 'Какие документы создаёт системный аналитик',
  'basics/git-overview': 'Что такое Git и зачем он нужен аналитику',
  'data/what-is-database': 'Что такое база данных',
  'data/sql-basics': 'Основы SQL (SELECT, JOIN, WHERE)',
  'data/json-xml': 'JSON и XML — форматы данных',
  'data/normalization': 'Нормализация БД',
  'data/nosql': 'NoSQL — когда и зачем',
  'data/data-modeling': 'Моделирование данных (ER)',
  'requirements/what-is-requirement': 'Что такое требование',
  'requirements/stakeholder-communication': 'Коммуникация со стейкхолдерами',
  'requirements/user-stories': 'User Stories',
  'requirements/bdd-scenarios': 'BDD-сценарии и критерии приёмки',
  'modeling/what-is-model': 'Что такое модель и зачем моделировать',
  'modeling/use-case-diagram': 'Use Case diagram — диаграмма вариантов использования',
  'modeling/sequence-diagram': 'Sequence diagram — диаграмма последовательности',
  'modeling/bpmn': 'BPMN — моделирование бизнес-процессов',
  'modeling/er-diagrams': 'ER-диаграммы (Entity-Relationship)',
  'modeling/state-diagram': 'State diagram (UML States)',
  'modeling/class-diagram': 'Class diagram для системного аналитика',
  'modeling/bpmn-advanced': 'BPMN — продвинутый уровень',
  'modeling/c4-context': 'C4 — Context diagram (уровень 1)',
  'modeling/c4-container': 'C4 — Container diagram (уровень 2)',
  'modeling/user-story-mapping': 'User Story Mapping',
  'modeling/impact-mapping': 'Impact Mapping',
  'modeling/dfd': 'Data Flow Diagram (DFD)',
  'modeling/component-diagram': 'UML — Component diagram',
  'integration/api-rest-basics': 'Основы REST API',
  'integration/api-openapi': 'Документирование API со спецификацией OpenAPI',
  'integration/api-design-detailed': 'Проектирование REST API — детально',
  'integration/api-versioning': 'Версионирование API',
  'integration/api-auth': 'Аутентификация и авторизация в API',
  'integration/api-soap-wsdl': 'SOAP / WSDL для работы с legacy-системами',
  'integration/async-message-queue': 'Асинхронное взаимодействие (Message Queue)',
  'integration/rabbitmq': 'RabbitMQ — очереди сообщений',
  'integration/kafka': 'Kafka — событийный streaming',
  'integration/event-driven-architecture': 'Event-Driven Architecture (введение)',
  'integration/event-storming': 'Event Storming',
  'architecture/what-is-architecture': 'Что такое архитектура ПО',
  'architecture/layered-architecture': 'Слоистая архитектура (layered)',
  'architecture/monolith-vs-microservices': 'Монолит vs Микросервисы',
  'architecture/microservices-patterns': 'Микросервисы — базовые паттерны',
  'architecture/cqrs': 'CQRS — Command Query Responsibility Segregation',
  'architecture/eda-detailed': 'Event-Driven Architecture (детально)',
  'architecture/solid': 'SOLID для системного аналитика',
  'architecture/adr': 'ADR — Architecture Decision Records',
  'process/sdlc-models': 'SDLC — модели разработки',
  'process/scrum-basics': 'Scrum — основы',
  'process/kanban-basics': 'Kanban — основы',
  'process/scrum-detailed': 'Scrum — роли, артефакты, события (детально)',
  'process/estimation': 'Оценка задач (story points, t-shirt sizing)',
  'process/retrospectives': 'Ретроспективы — техники и фасилитация',
  'process/agile-requirements': 'Требования в Agile',
  'soft/soft-skills': 'Что такое soft skills и зачем они аналитику',
  'soft/critical-thinking': 'Критическое мышление',
  'soft/business-writing': 'Деловая переписка и презентации',
  'http': 'HTTP — HyperText Transfer Protocol',
  'browser': 'Веб-браузер',
  'curl': 'cURL',
  'miro': 'Miro',
  'git': 'Git — контроль версий',
  'postgresql': 'PostgreSQL',
  'dbeaver': 'DBeaver',
  'plantuml': 'PlantUML',
  'drawio': 'Draw.io (diagrams.net)',
  'confluence': 'Confluence',
  'jira': 'Jira',
  'postman': 'Postman',
  'openapi': 'OpenAPI Specification (Swagger)',
  'scrum': 'Scrum',
  'figma': 'Figma',
  'kafka': 'Apache Kafka',
  'rabbitmq': 'RabbitMQ',
  'grooming': 'Проведение refinement (grooming) backlog',
  'test-checklist': 'Подготовка чек-листа для тестирования',
  'sql-query': 'Написать SQL-запрос по ТЗ',
  'describe-feature': 'Описать существующую фичу',
  'bug-report': 'Заведение баг-репорта',
  'acceptance-criteria': 'Написание acceptance criteria для user story',
  'write-user-story': 'Написание user story',
  'elicit-requirements': 'Сбор требований у стейкхолдера',
  'design-rest-api': 'Проектирование REST API',
  'conduct-stakeholder-interview': 'Проведение интервью со стейкхолдером',
  'find-analyst-in-team': 'Найти системного аналитика в знакомых',
  'describe-system-to-friend': 'Объяснить другу, что такое интернет',
  'design-database-schema': 'Проектирование схемы БД',
  'integrate-two-systems': 'Проектирование интеграции двух систем',
  'data/dwh-basics': 'Хранилища данных (DWH) — основы',
  'data/etl-basics': 'ETL — основы',
  'data/data-migration': 'Миграции данных — стратегии',
  'data/api-first-design': 'API-first design',
  'process/babok-overview': 'BABOK — обзор для системного аналитика',
  'process/requirements-management': 'Управление требованиями (Requirements Management)',
  'process/stakeholder-analysis': 'Анализ стейкхолдеров (Power/Interest Grid)',
  'process/cost-benefit-analysis': 'Cost-Benefit Analysis (CBA)',
  'process/risk-management': 'Управление рисками',
  'requirements/functional-requirements-detailed': 'Функциональные требования (детально)',
  'requirements/nfr': 'Нефункциональные требования (NFR)',
  'requirements/prioritization': 'Приоритизация требований (MoSCoW, Kano, RICE)',
  'requirements/use-cases-formal': 'Use Cases (формальные)',
  'requirements/user-story-mapping-req': 'User Story Mapping (требования)',
  'requirements/acceptance-criteria-detailed': 'Acceptance Criteria (детально)',
  'requirements/requirements-validation': 'Валидация требований',
  'requirements/change-management': 'Управление изменениями требований',
  'requirements/srs': 'SRS — Software Requirements Specification',
  'requirements/traceability': 'Трассировка требований',
  'requirements/decision-log': 'Decision Log',
  'soft/facilitation': 'Фасилитация встреч',
  'soft/business-writing-deep': 'Деловая переписка и коммуникация',
  'soft/workshop-techniques': 'Техники воркшопов',
  'soft/negotiations': 'Переговоры и работа с возражениями',
  'soft/mentoring': 'Менторство для аналитиков',
  'soft/coaching': 'Коучинг — базовые техники',
  'architecture/ddd-intro': 'DDD — Domain-Driven Design (введение)',
  'architecture/hexagonal-architecture': 'Hexagonal Architecture (Ports & Adapters)',
  'architecture/saga-pattern': 'Saga pattern — управление транзакциями',
  'architecture/strangler-fig': 'Strangler Fig — миграция legacy',
  'architecture/logging': 'Логирование — уровни, форматы, агрегация (ELK, Loki)',
  'architecture/monitoring': 'Мониторинг и observability — метрики, алерты, дашборды',
  'architecture/tracing': 'Distributed Tracing — трассировка запросов между сервисами',
  'architecture/authorization': 'Авторизация — RBAC, ABAC, политики доступа',
  'architecture/resilience-patterns': 'Resilience patterns — circuit breaker, retry, rate limiting',
  'architecture/caching': 'Кэширование — стратегии, Redis, CDN',
  'integration/enterprise-integration-patterns': 'Enterprise Integration Patterns (EIP)',
  'integration/api-gateway': 'API Gateway pattern',
  'integration/event-storming-advanced': 'Event Storming — продвинутый уровень',
  'specialization/ba-vs-sa': 'Бизнес-аналитик vs Системный аналитик',
  'specialization/data-analyst-path': 'Путь Data-аналитика',
  'specialization/solution-architect-path': 'Путь Solution-архитектора',
  'specialization/industry-analytics': 'Отраслевая аналитика (FinTech, Retail, Logistics)',
  'specialization/ai-analyst-intro': 'AI-аналитик — введение и роль',
  'specialization/ai-ml-basics': 'Основы ML для аналитика',
  'specialization/ai-ml-eda': 'EDA — разведочный анализ данных',
  'specialization/ai-ml-requirements': 'Сбор требований для ML-систем',
  'specialization/ai-ml-data': 'Данные для ML — качество, разметка, пайплайны',
  'specialization/ai-ml-metrics': 'Метрики ML-продуктов',
  'specialization/ai-llm-rag': 'LLM, RAG и промпт-инжиниринг',
  'specialization/ai-ethics': 'Этика, bias и регуляторика ИИ',
  'specialization/ai-ml-architecture': 'Архитектура AI-решений (MLOps, feature store)',
  'specialization/ai-agents-intro': 'AI-агенты — введение и архитектура',
  'specialization/ai-agents-multi': 'Мультиагентные системы — паттерны, оркестрация',
  'specialization/ai-agents-mcp': 'MCP — Model Context Protocol для подключения инструментов',
  'specialization/ai-agents-dev': 'Разработка AI-агентов — скилы, LSP, best practices',
  'llm': 'Large Language Model (LLM)',
  'langchain': 'LangChain',
  'huggingface': 'Hugging Face',
  'mlflow': 'MLflow',
  'vector-database': 'Vector Database (Qdrant, Pinecone, Weaviate)',
  'grpc': 'gRPC',
  'mcp': 'MCP — Model Context Protocol',
  'frame-ml-problem': 'Формулировка ML-задачи (ML problem framing)',
  'define-ml-metrics': 'Определение метрик ML-продукта',
  'design-rag-pipeline': 'Проектирование RAG-пайплайна',
  'design-agent-system': 'Проектирование AI-агента для продакшна',
  'docker': 'Docker — контейнеризация',
  'prometheus': 'Prometheus — сбор метрик',
  'redis': 'Redis — in-memory data store',
  'specialization/fintech-analyst-path': 'FinTech-аналитик — путь в финтех',
  'specialization/fintech-payments': 'Платёжные системы — как работают переводы',
  'specialization/fintech-regulation': 'Регуляторика в FinTech — ЦБ, 115-ФЗ, PCI DSS, PSD2',
  'specialization/fintech-protocols': 'Платёжные протоколы — ISO 8583, ISO 20022',
  'specialization/fintech-ledger': 'Double-entry ledger — бухгалтерский учёт в коде',
  'specialization/fintech-reconciliation': 'Сверка (reconciliation) — выявление расхождений',
  'specialization/fintech-open-banking': 'Open Banking / PSD2 — API, SCA, Berlin Group',
  'specialization/fintech-fraud': 'Фрод-мониторинг — антифрод-системы',
  'specialization/fintech-lending': 'Кредитный конвейер — loan origination, scoring, amortization',
  'iso20022': 'ISO 20022 — финансовые сообщения',
  'pci-dss': 'PCI DSS — стандарт безопасности данных карт',
  'swift': 'SWIFT — межбанковские сообщения',
  'fintech-design-payment': 'Проектирование платёжной интеграции (BNPL)',
  'fintech-reconciliation': 'Проектирование системы сверки',
  'fintech-pci-checklist': 'PCI DSS compliance checklist для платёжного шлюза',
  'specialization/ecommerce-retail-path': 'E-commerce — роль, специфика, путь',
  'specialization/ecommerce-oms': 'OMS — Order Management System',
  'specialization/ecommerce-catalog': 'Каталог товаров и инвентаризация',
  'specialization/ecommerce-pricing': 'Ценообразование, промо и скидки',
  'specialization/ecommerce-marketplace': 'Маркетплейсы — модель и интеграции',
  'specialization/ecommerce-fulfillment': 'Фулфилмент и логистика',
  'specialization/ecommerce-loyalty': 'Программы лояльности и кешбэк',
  'specialization/ecommerce-analytics': 'Retail-аналитика и персонализация',
  'elasticsearch': 'Elasticsearch — поиск и каталог',
  'erp': 'ERP-системы (SAP, 1С, Oracle)',
  'wms': 'WMS — складские системы',
  'ecommerce-design-catalog': 'Проектирование каталога товаров',
  'ecommerce-oms-flow': 'Проектирование OMS (статусы и переходы)',
  'ecommerce-loyalty': 'Проектирование программы лояльности',
  'specialization/telecom-path': 'Telecom — роль, специфика, путь',
  'specialization/telecom-bss-oss': 'BSS/OSS — архитектура Telecom-систем',
  'specialization/telecom-billing': 'Billing и Charging (online/offline)',
  'specialization/telecom-crm-order': 'CRM и Order Management в Telecom',
  'specialization/telecom-provisioning': 'Provisioning и активация услуг',
  'specialization/telecom-regulations': 'Регуляторика в Telecom (СОРМ, ПД, лицензии)',
  'specialization/telecom-mvno': 'MVNO — модель виртуальных операторов',
  'specialization/telecom-5g-iot': '5G, IoT и новые технологии в Telecom',
  'tmforum': 'TM Forum Open API — стандарт Telecom',
  'diameter': 'Diameter — базовый протокол Telecom',
  'kubernetes': 'Kubernetes — оркестрация контейнеров',
  'telecom-design-billing': 'Проектирование биллинговой модели',
  'telecom-oss-integration': 'Интеграция OSS-систем (TM Forum API)',
  'telecom-compliance': 'Чек-лист соответствия регулятору для оператора связи',
  'specialization/govtech-path': 'GovTech — роль, специфика, путь',
  'specialization/govtech-gis-architecture': 'Архитектура ГИС',
  'specialization/govtech-portal': 'Госуслуги и порталы — проектирование',
  'specialization/govtech-smev': 'СМЭВ — межведомственное взаимодействие',
  'specialization/govtech-import-substitution': 'Импортозамещение и реестр ПО',
  'specialization/govtech-security': 'Безопасность и аттестация (ФСТЭК)',
  'specialization/govtech-procurement': 'Госзакупки (44-ФЗ, 223-ФЗ)',
  'specialization/govtech-edo': 'ЭДО и документооборот в госсекторе',
  'smev': 'СМЭВ — межведомственное взаимодействие',
  'crypto': 'Криптография (ГОСТ, УКЭП, PKI)',
  'astra-linux': 'Astra Linux — ОС для импортозамещения',
  'gov-design-service': 'Проектирование госуслуги',
  'gov-smev-integration': 'Интеграция ГИС с СМЭВ 3',
  'gov-security-audit': 'Чек-лист аттестации ГИС (ФСТЭК)',
  'specialization/medtech-path': 'MedTech — роль, специфика, карьерный путь в медицине и фарме',
  'specialization/medtech-emk': 'ЭМК — электронные медицинские карты',
  'specialization/medtech-mis': 'МИС — медицинские информационные системы',
  'specialization/medtech-lis': 'ЛИС — лабораторные информационные системы',
  'specialization/medtech-pharma': 'Фарма — учёт лекарств и маркировка (Честный ЗНАК)',
  'specialization/medtech-telemedicine': 'Телемедицина и дистанционные консультации',
  'specialization/medtech-pacs': 'PACS / DICOM — медицинские изображения',
  'specialization/medtech-regulations': 'Регуляторика в медицине (323-ФЗ, 152-ФЗ, оборот лекарств)',
  'hl7': 'HL7 FHIR — медицинский обмен данными',
  'emias': 'ЕГИСЗ / ЕМИАС — госмедицина',
  'dicom': 'DICOM — стандарт медицинских изображений',
  'medtech-design-emk': 'Проектирование электронной медкарты (ЭМК)',
  'medtech-lis-integration': 'Интеграция ЛИС с МИС',
  'medtech-compliance': 'Чек-лист соответствия 323-ФЗ',
  'specialization/logistics-path': 'Логистика — роль, специфика, карьерный путь',
  'specialization/logistics-tms': 'TMS — система управления перевозками',
  'specialization/logistics-wms': 'Складская логистика и WMS',
  'specialization/logistics-last-mile': 'Доставка последней мили и трекинг',
  'specialization/logistics-routing': 'Маршрутизация и оптимизация',
  'specialization/logistics-edo': 'ЭДО и документооборот в логистике',
  'specialization/logistics-integrations': 'Интеграции с маркетплейсами и курьерами',
  'specialization/logistics-analytics': 'Аналитика в логистике',
  'tms': 'TMS — транспортные системы',
  'geodata': 'Геоданные (карты, маршрутизация)',
  'edi': 'EDI — электронный обмен данными',
  'logistics-design-delivery': 'Проектирование системы доставки',
  'logistics-integration-courier': 'Интеграция с курьерской службой',
  'logistics-optimization': 'Оптимизация маршрутов доставки',
  'specialization/gamedev-path': 'GameDev — роль, специфика, карьерный путь',
  'specialization/gamedev-gdd': 'GDD и документация в GameDev',
  'specialization/gamedev-architecture': 'Архитектура игровых проектов',
  'specialization/gamedev-matchmaking': 'Матчмейкинг и игровые сессии',
  'specialization/gamedev-economy': 'Игровая экономика и баланс',
  'specialization/gamedev-social': 'Социальные механики и друзья',
  'specialization/gamedev-monetization': 'Монетизация — IAP, реклама, подписки',
  'specialization/gamedev-liveops': 'LiveOps — управление живым продуктом',
  'specialization/gamedev-analytics': 'Game Analytics',
  'specialization/gamedev-sdk': 'SDK-интеграции в играх',
  'specialization/gamedev-publishing': 'Публикация и платформы (App Store / Google Play)',
  'unity': 'Unity / Unreal Engine',
  'photon': 'Photon / Netcode — мультиплеер',
  'appsflyer': 'AppsFlyer / Adjust — mobile analytics',
  'firebase': 'Firebase — экосистема для мобильных игр',
  'gamedev-design-economy': 'Проектирование игровой экономики',
  'gamedev-matchmaking-flow': 'Проектирование матчмейкинга',
  'gamedev-liveops': 'Проектирование LiveOps-кампании',
  'specialization/socnet-path': 'Соцсети и контентные платформы — путь',
  'specialization/socnet-feed': 'Лента контента — feed, ranking, рекомендации',
  'specialization/socnet-messenger': 'Мессенджеры и real-time коммуникации',
  'specialization/socnet-moderation': 'Модерация контента и безопасность',
  'specialization/socnet-graph': 'Социальный граф и друзья',
  'specialization/socnet-monetization': 'Монетизация соцсетей — реклама, подписки',
  'specialization/socnet-platform': 'Платформа контента — видео, музыка, stories',
  'specialization/socnet-eco': 'Платформенные механики — API, SDK, маркетплейс',
  'recommendation': 'Рекомендательные системы (ML)',
  'websocket': 'WebSocket / SSE — real-time протоколы',
  'cdn': 'CDN — доставка контента',
  'socnet-design-feed': 'Проектирование ленты контента',
  'socnet-moderation-flow': 'Проектирование системы модерации',
  'socnet-recommendations': 'Проектирование рекомендательной системы',
};

const SHORT_LOOKUP: Record<string, string> = {};
for (const [key, label] of Object.entries(LABELS)) {
  const short = key.split('/').pop();
  if (short && !SHORT_LOOKUP[short]) {
    SHORT_LOOKUP[short] = label;
  }
}

export function getDocLabel(id: string): string {
  return LABELS[id] || SHORT_LOOKUP[id] || SHORT_LOOKUP[id.split('/').pop() ?? ''] || id.split('/').pop() || id;
}
