const LABELS: Record<string, string> = {
  'basics/what-is-software': 'Что такое программное обеспечение',
  'basics/how-computer-works': 'Как работает компьютер',
  'basics/what-is-programming': 'Что такое программирование',
  'basics/who-is-system-analyst': 'Кто такой системный аналитик',
  'basics/client-server': 'Клиент-серверная архитектура',
  'basics/client-server-basics': 'Клиент-серверная архитектура',
  'basics/what-is-api': 'Что такое API',
  'basics/what-is-protocol': 'Что такое протокол взаимодействия',
  'basics/it-roles': 'Какие есть роли в IT-команде',
  'basics/sa-day-in-life': 'Как выглядит рабочий день системного аналитика',
  'basics/what-is-data': 'Что такое данные, информация, знания',
  'basics/what-is-network': 'Что такое интернет и компьютерная сеть',
  'basics/what-is-os': 'Что такое операционная система',
  'basics/what-is-app-types': 'Какими бывают приложения: веб, мобайл, десктоп',
  'basics/what-is-sdlc': 'Как разрабатывают программное обеспечение (SDLC)',
  'basics/what-is-database-basics': 'Как устроены базы данных',
  'basics/what-is-testing': 'Как тестируют программное обеспечение',
  'basics/what-is-sa-documentation': 'Какие документы создаёт системный аналитик',
  'basics/git-overview': 'Что такое Git и зачем он нужен аналитику',
  'data/what-is-database': 'Что такое база данных',
  'data/sql-basics': 'Основы SQL (SELECT, JOIN, WHERE)',
  'data/json-xml': 'JSON и XML — форматы данных',
  'data/normalization': 'Нормализация БД',
  'data/nosql': 'NoSQL — когда и зачем',
  'data/data-modeling': 'Моделирование данных (ER)',
  'requirements/what-is-requirement': 'Что такое требование',
  'requirements/stakeholder-communication': 'Коммуникация со стейкхолдерами',
  'requirements/user-stories': 'User Stories',
  'requirements/bdd-scenarios': 'BDD-сценарии и критерии приёмки',
  'modeling/what-is-model': 'Что такое модель и зачем моделировать',
  'modeling/use-case-diagram': 'Use Case diagram — диаграмма вариантов использования',
  'modeling/sequence-diagram': 'Sequence diagram — диаграмма последовательности',
  'modeling/bpmn': 'BPMN — моделирование бизнес-процессов',
  'modeling/er-diagrams': 'ER-диаграммы (Entity-Relationship)',
  'modeling/state-diagram': 'State diagram (UML States)',
  'modeling/class-diagram': 'Class diagram для системного аналитика',
  'modeling/bpmn-advanced': 'BPMN — продвинутый уровень',
  'modeling/c4-context': 'C4 — Context diagram (уровень 1)',
  'modeling/c4-container': 'C4 — Container diagram (уровень 2)',
  'modeling/user-story-mapping': 'User Story Mapping',
  'modeling/impact-mapping': 'Impact Mapping',
  'modeling/dfd': 'Data Flow Diagram (DFD)',
  'modeling/component-diagram': 'UML — Component diagram',
  'integration/api-rest-basics': 'Основы REST API',
  'integration/api-openapi': 'Документирование API со спецификацией OpenAPI',
  'integration/api-design-detailed': 'Проектирование REST API — детально',
  'integration/api-versioning': 'Версионирование API',
  'integration/api-auth': 'Аутентификация и авторизация в API',
  'integration/api-soap-wsdl': 'SOAP / WSDL для работы с legacy-системами',
  'integration/async-message-queue': 'Асинхронное взаимодействие (Message Queue)',
  'integration/rabbitmq': 'RabbitMQ — очереди сообщений',
  'integration/kafka': 'Kafka — событийный streaming',
  'integration/event-driven-architecture': 'Event-Driven Architecture (введение)',
  'integration/event-storming': 'Event Storming',
  'architecture/what-is-architecture': 'Что такое архитектура ПО',
  'architecture/layered-architecture': 'Слоистая архитектура (layered)',
  'architecture/monolith-vs-microservices': 'Монолит vs Микросервисы',
  'architecture/microservices-patterns': 'Микросервисы — базовые паттерны',
  'architecture/cqrs': 'CQRS — Command Query Responsibility Segregation',
  'architecture/eda-detailed': 'Event-Driven Architecture (детально)',
  'architecture/solid': 'SOLID для системного аналитика',
  'architecture/adr': 'ADR — Architecture Decision Records',
  'process/sdlc-models': 'SDLC — модели разработки',
  'process/scrum-basics': 'Scrum — основы',
  'process/kanban-basics': 'Kanban — основы',
  'process/scrum-detailed': 'Scrum — роли, артефакты, события (детально)',
  'process/estimation': 'Оценка задач (story points, t-shirt sizing)',
  'process/retrospectives': 'Ретроспективы — техники и фасилитация',
  'process/agile-requirements': 'Требования в Agile',
  'soft/soft-skills': 'Что такое soft skills и зачем они аналитику',
  'soft/critical-thinking': 'Критическое мышление',
  'soft/business-writing': 'Деловая переписка и презентации',
  'http': 'HTTP — HyperText Transfer Protocol',
  'browser': 'Веб-браузер',
  'curl': 'cURL',
  'miro': 'Miro',
  'git': 'Git — контроль версий',
  'postgresql': 'PostgreSQL',
  'dbeaver': 'DBeaver',
  'plantuml': 'PlantUML',
  'drawio': 'Draw.io (diagrams.net)',
  'confluence': 'Confluence',
  'jira': 'Jira',
  'postman': 'Postman',
  'openapi': 'OpenAPI Specification (Swagger)',
  'scrum': 'Scrum',
  'figma': 'Figma',
  'kafka': 'Apache Kafka',
  'rabbitmq': 'RabbitMQ',
  'grooming': 'Проведение refinement (grooming) backlog',
  'test-checklist': 'Подготовка чек-листа для тестирования',
  'sql-query': 'Написать SQL-запрос по ТЗ',
  'describe-feature': 'Описать существующую фичу',
  'bug-report': 'Заведение баг-репорта',
  'acceptance-criteria': 'Написание acceptance criteria для user story',
  'write-user-story': 'Написание user story',
  'elicit-requirements': 'Сбор требований у стейкхолдера',
  'design-rest-api': 'Проектирование REST API',
  'conduct-stakeholder-interview': 'Проведение интервью со стейкхолдером',
  'find-analyst-in-team': 'Найти системного аналитика в знакомых',
  'describe-system-to-friend': 'Объяснить другу, что такое интернет',
  'design-database-schema': 'Проектирование схемы БД',
  'integrate-two-systems': 'Проектирование интеграции двух систем',
  'data/dwh-basics': 'Хранилища данных (DWH) — основы',
  'data/etl-basics': 'ETL — основы',
  'data/data-migration': 'Миграции данных — стратегии',
  'data/api-first-design': 'API-first design',
  'process/babok-overview': 'BABOK — обзор для системного аналитика',
  'process/requirements-management': 'Управление требованиями (Requirements Management)',
  'process/stakeholder-analysis': 'Анализ стейкхолдеров (Power/Interest Grid)',
  'process/cost-benefit-analysis': 'Cost-Benefit Analysis (CBA)',
  'process/risk-management': 'Управление рисками',
  'requirements/functional-requirements-detailed': 'Функциональные требования (детально)',
  'requirements/nfr': 'Нефункциональные требования (NFR)',
  'requirements/prioritization': 'Приоритизация требований (MoSCoW, Kano, RICE)',
  'requirements/use-cases-formal': 'Use Cases (формальные)',
  'requirements/user-story-mapping-req': 'User Story Mapping (требования)',
  'requirements/acceptance-criteria-detailed': 'Acceptance Criteria (детально)',
  'requirements/requirements-validation': 'Валидация требований',
  'requirements/change-management': 'Управление изменениями требований',
  'requirements/srs': 'SRS — Software Requirements Specification',
  'requirements/traceability': 'Трассировка требований',
  'requirements/decision-log': 'Decision Log',
  'soft/facilitation': 'Фасилитация встреч',
  'soft/business-writing-deep': 'Деловая переписка и коммуникация',
  'soft/workshop-techniques': 'Техники воркшопов',
  'soft/negotiations': 'Переговоры и работа с возражениями',
  'soft/mentoring': 'Менторство для аналитиков',
  'soft/coaching': 'Коучинг — базовые техники',
  'architecture/ddd-intro': 'DDD — Domain-Driven Design (введение)',
  'architecture/hexagonal-architecture': 'Hexagonal Architecture (Ports & Adapters)',
  'architecture/saga-pattern': 'Saga pattern — управление транзакциями',
  'architecture/strangler-fig': 'Strangler Fig — миграция legacy',
  'integration/enterprise-integration-patterns': 'Enterprise Integration Patterns (EIP)',
  'integration/api-gateway': 'API Gateway pattern',
  'integration/event-storming-advanced': 'Event Storming — продвинутый уровень',
  'specialization/ba-vs-sa': 'Бизнес-аналитик vs Системный аналитик',
  'specialization/data-analyst-path': 'Путь Data-аналитика',
  'specialization/solution-architect-path': 'Путь Solution-архитектора',
  'specialization/industry-analytics': 'Отраслевая аналитика (FinTech, Retail, Logistics)',
};

const SHORT_LOOKUP: Record<string, string> = {};
for (const [key, label] of Object.entries(LABELS)) {
  const short = key.split('/').pop();
  if (short && !SHORT_LOOKUP[short]) {
    SHORT_LOOKUP[short] = label;
  }
}

export function getDocLabel(id: string): string {
  return LABELS[id] || SHORT_LOOKUP[id] || SHORT_LOOKUP[id.split('/').pop() ?? ''] || id.split('/').pop() || id;
}
